### ISSUE TITLE
Normalize.css test with kraken fails

### ISSUE THREAD

**Issue by yckart** [cferdinandi/kraken#211]
Since normalize.css (v3.0.0+) uses a clever test-file, it's easy to compare with other frameworks/libraries/whatever. Here's a quick port for kraken: http://jsbin.com/bigiyoweka/1

Fails at some points, mostly on box-model related stuff...

**Update**
Oops, the missing normalize test file: http://necolas.github.io/normalize.css/latest/test.html

**Comment by cferdinandi** [comment]
While I've incorporated elements of `normalize.css` into Kraken, it's not my primary base code at the moment, so I'm not surprised. I have also universally applied `box-sizing: border-box`, so I'm not surprised some elements fail there.

I do plan to switch to Normalize at some point, but now, this is unsurprising.
