### ISSUE TITLE
Switch from Meyer's CSS Reset to normalize.css

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/kraken#213]

**Comment by yckart** [comment]
Yap, that's an important step. Currently we are unable to enjoy the full power of Kraken. Resetting our css, let us drive (mostly) in more trouble, than solutions :(

**Comment by cferdinandi** [comment]
Glad to hear you're in support of this move. I should elaborate: It's driven largely by my move to inlining critical CSS. Meyer's Reset, when inlined, has higher specificity than you would want, and causes some unintended behaviors.

**Comment by cferdinandi** [comment]
Coming in v7.x.x
