### ISSUE TITLE
clean install won't go through: phantomjs missing?

### ISSUE THREAD

**Issue by myhd** [cferdinandi/kraken#240]
When running `npm install`, I get a warning saying 

> UNMET PEER DEPENDENCY phantomjs@>=1.9
> npm WARN EPEERINVALID karma-phantomjs-launcher@0.2.1 requires a peer of phantomjs@>=1.9 but none was installed.

This is on a newly setup machine, no npm installed beforehand.  npm version is 3.3.9. 
Is this desired behavior? I would fix it myself, but I do not know how. Thank you!

**Comment by cferdinandi** [comment]
@myhd Thanks for the catch. Same issue as noted here: https://github.com/cferdinandi/gulp-boilerplate/issues/43

I need to explicitly add PhantomJS as a dependency in the `package.json` file. As a temporary fix, you can [manually install PhantomJS](http://phantomjs.org/).

**Comment by cferdinandi** [comment]
Should be addressed in v7.1.1
