### ISSUE TITLE
html files in src/ do not compile to dist/

### ISSUE THREAD

**Issue by myhd** [cferdinandi/kraken#241]
In src/, changed files in subfolders (graphics, svgs etc) *do* go to the dist/ folder when `gulp watch`ing. HTML and md files, however, do not. Is this by design?

**Comment by cferdinandi** [comment]
Interesting use case I hadn't considered. In previous iterations, there was a `static` directory in `src` for files that should be copied as-is over to the `dist` folder, but it was removed in favor of a dedicated `img` folder. I may have to bring it back.

HTML/md files placed in `src` > `docs` will copy over (with the md files being compiled into HTML).

**Comment by myhd** [comment]
I was under the impression that the actual development of "pages", e.g. HTML, PHP etc, was to happen in _src/_, and it also be optimized through the gulp mechanism to _dist/_. No? Which workflow would you propose for developing with Kraken? Or, in other words: where would I put my actual HTML docs? I used an older version where gulp was not used yet.

**Comment by cferdinandi** [comment]
Ah I see. So, Kraken is really designed to be a bit barebones. I personally but my static HTML/md in `docs`, but I literally use that to create documentation. I work primarily with WordPress, so all of my PHP files sit in the root directory for my projects, along side the `dist`, `src`, and `test` directories.

Based on this convo, I think I need to add some functionality to do a raw copy/paste directory in `src`, but for now, how you handle your HTML is left up to the discretion of the developer.

**Comment by cferdinandi** [comment]
Fixed in https://github.com/cferdinandi/kraken/pull/244
