### ISSUE TITLE
Keel PhotoSwipe Caption for thumbnails in gallery

### ISSUE THREAD

**Issue by melbournevijay** [cferdinandi/kraken#272]
On https://marellagm.com.au/engineered-stone/ the gallery thumbnails don't display a caption. Whereas, when you click on a thumbnail, the lightbox version does display a caption 
https://marellagm.com.au/engineered-stone/#&gid=1&pid=2 

How do I display captions for the gallery thumbnails (CSS, JS code or is there a setting I am missing)?

**Comment by cferdinandi** [comment]
Can you move this over to https://github.com/cferdinandi/keel/?

Thanks.
