### ISSUE TITLE
@extend issue with _grid.scss on line 97

### ISSUE THREAD

**Issue by escapehatch** [cferdinandi/kraken#275]
https://github.com/cferdinandi/kraken/blob/9612f781ad5d92f318114de89a08682e51c3eaa2/src/sass/components/_grid.scss#L97

CodeKit shows Libsass: Error: You may not @extend an outer selector from within @media.
       You may only @extend selectors within the same directive.
       From "@extend %grid-with-padding" on line 110 of kraken-8/src/sass/components/_grid.scss
        on line 97 of kraken-8/src/sass/components/_grid.scss
>> 		%grid-with-padding {

   --^

**Comment by cferdinandi** [comment]
This should now be fixed with v8.0.3

**Comment by escapehatch** [comment]
Hi Chris,

great. Thank you.  

Best,
Tom
