### ISSUE TITLE
Fix typo in docs

### ISSUE THREAD

**Issue by florianbouvot** [cferdinandi/kraken#280]
@cferdinandi I think there is some small issue in the docs : 

1. `.text-tall` instead of `.text-large`

> Because Kraken uses relative sizing, you should always apply .text-tall and .text-small classes to a <span> element and not directly to a <p>. Otherwise, your spacing will get all messed up. The .text-* classes can be found in _overrides.scss for better cascade inheritance.

*in Typography section: https://cferdinandi.github.io/kraken/components.html#typography*

2. Unneeded </a> at the beginning of code sample

```
</a><a class="visually-hidden focusable" href="#main">Skip to content</a>
```

*in Visibility section: https://cferdinandi.github.io/kraken/components.html#alignment-spacing--visibility*

3. Rename `.screen-reader` classes to `.visually-hidden` in Tabindex & Focus Styles section

**Comment by cferdinandi** [comment]
Thank you! There were some conflicts with my markdown parsers and some unclosed HTML elements. Appreciate you letting me know about this!
