### ISSUE TITLE
Issue getting floats to work

### ISSUE THREAD

**Issue by escapehatch** [cferdinandi/kraken#285]
The .float-center and .float-right seem to no longer be working. Using floats also appears to alter width of a column.
https://cferdinandi.github.io/kraken/components.html#alignment-spacing--visibility

**Comment by cferdinandi** [comment]
These should not be used with the grid layout. 

They’re intended for use with inline elements, things like buttons or images where you want text or other elements to wrap around them.

is that how you’re using them?

**Comment by escapehatch** [comment]
Oh, I see. Thank you, Chris! Is there another approach you could suggest to get a column to align center on the grid?

**Comment by cferdinandi** [comment]
Yes, I would use the new classes for pushing grid events over one direction or another. https://cferdinandi.github.io/kraken/components.html#content-choreography

**Comment by escapehatch** [comment]
Thank you 😊
