### ISSUE TITLE
H4 is uppercase

### ISSUE THREAD

**Issue by tyler-vs** [cferdinandi/kraken#289]
Would it be better to have an `.uppercase` utility class?

https://github.com/cferdinandi/kraken/blob/83ea39b089acbefcc217f6c5685acabc06b484ce/src/scss/components/_typography.scss#L154C1-L158C2

**Comment by cferdinandi** [comment]
A few things...

1. That's included just as a way to make the `h4` heading, which is the same size as `h5` and `h6`, a bit more visually significant.
2. This is a boilerplate, so the whole point is that you take it and modify it as desired. I'm very purposefully _not_ trying to meet the needs of everyone.
3. I use this as the starting point for my own projects. I sometimes add a `.text-uppercase` utility class (if I need one), but when I want a heading to look a certain way every time, I generally style the element.
